version: "3.8"

services:
  app:
    container_name: backend-dev
    image: backend-dev
    build:
      context: .
      target: development
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "4000:4000"
  db:
    container_name: backend-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cvwo
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
