# Label API

### 
# Constants
@baseURL = http://localhost:4000/label

###
# Get current user's labels
GET {{baseURL}}/current

###
# Get labels
GET {{baseURL}}/


###
# Get label by id
GET {{baseURL}}/1

###
# Add label to task ids given
POST {{baseURL}}
Content-Type: application/json

{
    "name": "potato",
    "tasks": [2]
}

###
# Update label
PATCH {{baseURL}}/2
Content-Type: application/json

{
    "name":"asd",
    "tasks": [],
}

### 
# Delete label
DELETE {{baseURL}}/2

###
# archive/unarchive label
PUT {{baseURL}}/2/archive
Content-Type: application/json

{
    "remove": true
}