# users API

###
# baseURL
@baseURL = http://localhost:3000/list

###
# Get current user's lists
GET {{baseURL}}/list

###
# Add list for current user
POST {{baseURL}}/list/create
Content-Type: application/json

{
    "title": "potato"
}

###
# Archive list
POST {{baseURL}}/list/archive
Content-Type: application/json

{
    "id": 5,
    "delete": true
}

###
# Unarchive list
POST {{baseURL}}/list/unarchive
Content-Type: application/json

{
    "id": 2
}


###
# Update list
PATCH  {{baseURL}}/list/update
Content-Type: application/json

{
    "id": 2,
    "title": "sample",
    "tasks": [],
    "users": [1,2]
}