# List API

### 
# Constants
@baseURL = http://localhost:4000/list

###
# Get current user's lists
GET {{baseURL}}

###
# Add list for current user
POST {{baseURL}}
Content-Type: application/json

{
    "title": "potato2"
}

###
# Archive/Unarchive list
PUT {{baseURL}}/1/archive
Content-Type: application/json

{
    "archive": false
}

###
# Update list
PATCH  {{baseURL}}/1
Content-Type: application/json

{
    "title": "egg",
    "tasks": [],
    "users": []
}

###
# Delete list
DELETE {{baseURL}}/1