# users API

###
# baseURL
@baseURL = http://localhost:3000/task

### 
# time
@time = "2022-01-01T15:39:24.022Z"

###
# Get current user's tasks
GET {{baseURL}}?listId=2

###
# Add task to list with given listId
POST {{baseURL}}
Content-Type: application/json

{
    "name": "2",
    "startDate": {{time}},
    "dueDate": {{time}},
    "listId": 2
}

###
# Update task 
PATCH {{baseURL}}/1
Content-Type: application/json

{
    "name":"asd",
    "startDate":"",
    "dueDate":"",
    "done": true,
    "labels": [],
    "listId": 1
}