# Task API

### 
# Constants
@baseURL = http://localhost:3000/task
@time = "2022-01-01T15:39:24.022Z"

###
# Get current user's tasks
GET {{baseURL}}?listId=1


###
# Get task by id
GET {{baseURL}}/1

###
# Add task to list with given listId
POST {{baseURL}}
Content-Type: application/json

{
    "name": "egg",
    "startDate": {{time}},
    "dueDate": {{time}},
    "listId": 2
}

###
# Update task 
PATCH {{baseURL}}/4
Content-Type: application/json

{
    "name":"asd",
    "startDate":"",
    "dueDate":"",
    "done": true,
    "labels": [],
    "listId": 1
}

### 
# Delete task
DELETE {{baseURL}}/3

###
# Archive/Unarchive task
PUT {{baseURL}}/1/archive
Content-Type: application/json

{
    "archive": true
}