# User API

###
# Constants
@baseURL = http://localhost:4000/user

###
# Get current user
GET {{baseURL}}/current

###
# Get current user
GET {{baseURL}}/2

###
# Logout
POST {{baseURL}}/logout

###
# Register
POST {{baseURL}}/
Content-Type: application/json

{
    "username": "marcus",
    "email": "potato@gmail.com",
	"password": "qwer1234"
}

###
# Login
POST {{baseURL}}/login
Content-Type: application/json

{
    "username": "marcus",
    "email": "potato@gmail.com",
	"password": "qwer1234"
}

### 
# Update
PATCH {{baseURL}}/2
Content-Type: application/json

{
    "username": "test",
    "email": "potato@gmail.com"
}

###
# Delete
DELETE {{baseURL}}/1